[TTAHUB-1002] Update Objectives when Recipients Change
HHS/Head-Start-TTADP pull request #1031
Opened 2022-09-13 13:15 UTC by AdamAdHocTeam

## Description of change

This fixes two bugs when a recipient is added to an existing AR report.
- When it attempts to find a existing goal it excludes null template ids.
- If the goal id doesn't match the objective goal id we need to create a new objective.

## How to test

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1002

## Checklists

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

2022-09-13 20:46 UTC, nvms approved these changes
I created a recipient report with one recipient, added a goal and objective and returned to the summary stage to add a second recipient and verified that the `Goals`, `Objectives`, `ActivityReportGoals` and `ActivityReportObjectives` tables are all updated with an additional row. Removing the second recipient removes that additional row in all above tables.

2022-09-14 17:34 UTC, thewatermethod requested changes
Works pretty good - found one small issue. Steps to reproduce:

1) Add recipient A, save.
2) Select existing goal and objective, save.
3) Looks good in DB.
4) Go back to activity summary. Add recipient B. Save.
5) Looks good in DB.
6) Go back to activity summary. Remove recipient A. Add recipient C. Save.

We get a 500 error on the /POST and the backend throws this error:
![sequelize backend error](https://user-images.githubusercontent.com/3288586/190223767-adf14dbf-f23d-41de-9d39-38c5b4d140fe.png)

2022-09-14 20:14 UTC, AdamAdHocTeam commented
> Works pretty good - found one small issue. Steps to reproduce:
> 
> 1. Add recipient A, save.
> 2. Select existing goal and objective, save.
> 3. Looks good in DB.
> 4. Go back to activity summary. Add recipient B. Save.
> 5. Looks good in DB.
> 6. Go back to activity summary. Remove recipient A. Add recipient C. Save.
> 
> We get a 500 error on the /POST and the backend throws this error: ![sequelize backend error](https://user-images.githubusercontent.com/3288586/190223767-adf14dbf-f23d-41de-9d39-38c5b4d140fe.png)

Let me know when you have a moment. I cannot reproduce this issue.

2022-09-16 15:20 UTC, thewatermethod approved these changes

2022-09-16 15:37 UTC, merged