[TTAHUB-1003] put back programs on approved page and csv export
HHS/Head-Start-TTADP pull request #1032
Opened 2022-09-13 21:23 UTC by AdamAdHocTeam

## Description of change

We need to add back the program type to both the approved report and csv export.

## How to test

View an approved report and export the csv

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1003

## Checklists

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

2022-09-14 16:02 UTC, nvms approved these changes
lg, verified program type shows on an approved report as well as csv export

2022-09-14 17:14 UTC, thewatermethod requested changes
😭  Multi-recipient reports no longer show all recipients on either the approved AR view or the CSV

2022-09-20 20:59 UTC, thewatermethod commented on src/services/activityReports.js
> +      out why joining programs to grants causes issues.
🤣

2022-09-20 21:19 UTC, thewatermethod approved these changes

2022-09-21 15:49 UTC, nvms approved these changes

2022-09-21 16:16 UTC, merged