[TTAHUB-1641] Auto generate logical diagram
HHS/Head-Start-TTADP pull request #1488
Opened 2023-04-24 10:32 UTC by GarrettEHill

## Description of change

## How to test

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1641

## Checklists

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

2023-05-03 17:20 UTC, thewatermethod approved these changes
Great!

2023-05-03 19:16 UTC, AdamAdHocTeam approved these changes
Looks good although I wasn't able to get the docker image to run. I did see changes to the schema files under docs.

2023-05-03 20:36 UTC, merged

2023-05-04 01:46 UTC, hardwarehuman requested changes

2023-05-04 01:46 UTC, hardwarehuman commented on src/migrations/20230424000000-correct-model-db-misalignment.js
> +    await queryInterface.sequelize.transaction((transaction) => (queryInterface.removeColumn('Goals', 'rtrOrder', { transaction })));
This vestigial `down` needs to be removed

2023-05-04 01:46 UTC, hardwarehuman commented on src/migrations/20230424000000-correct-model-db-misalignment.js
> +        await queryInterface.dropTable(`ZAL${table}`, { transaction });
Where was `ObjectiveTemplateRoles` removed? I don't see it in `main`

2023-05-04 01:50 UTC, hardwarehuman commented on src/migrations/20230424000000-correct-model-db-misalignment.js
> +        await queryInterface.dropTable(`ZAL${table}`, { transaction });
Wait, we're not trying to remove the table, I see. You can ignore this one.