[TTAHUB-448] Specialist name filter
HHS/Head-Start-TTADP pull request #1615
Opened 2023-07-10 18:40 UTC by AdamAdHocTeam

## Description of change

Add a 'Specialist name' filter to the AR landing and Regional Dashboard. We only add this filter if the user has the ability to approve reports.

## How to test

Create a user with the ability to approve reports. On both the AR Landing and Regional Dashboard create a filter using the new 'Specialist name' filter. Ensure relevant results are returned. 

Create a user who does NOT have the ability to approve reports. Both the AR Landing and Regional Dashboard should NOT have the ability to add the 'Specialist name' filter.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-448

## Checklists

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

2023-07-10 23:05 UTC, GarrettEHill approved these changes

2023-07-11 14:25 UTC, thewatermethod commented
Do we want to bump .ttahub-filter-menu-item [name="condition"] to have a width of 150px instead of 140px?

(Screenshots show a width of 140, cutting off collaborator, and then a width of 150, showing it)

![Screenshot 2023-07-11 at 10 24 13 AM](https://github.com/HHS/Head-Start-TTADP/assets/3288586/8eadcf4c-7092-4659-abe0-d8addf0cd2e6)

![Screenshot 2023-07-11 at 10 25 05 AM](https://github.com/HHS/Head-Start-TTADP/assets/3288586/3052041d-00a5-436a-89e7-9a70efc70d18)

2023-07-11 14:31 UTC, thewatermethod requested changes
Seem to have found a bug. See attached video

https://github.com/HHS/Head-Start-TTADP/assets/3288586/255fbc76-2f33-4844-9edc-798244e49e23

2023-07-11 17:15 UTC, thewatermethod commented on src/scopes/activityReport/specialistName.js
> +import { filterAssociation } from './utils';
filterAssociation is unused

2023-07-11 17:20 UTC, thewatermethod commented
Works more like I'd expect now - once that test is resolved, I'm good to approve

2023-07-11 18:24 UTC, thewatermethod approved these changes

2023-07-11 18:37 UTC, merged