[TTAHUB-1583] Update "Child Incidents"
HHS/Head-Start-TTADP pull request #1682
Opened 2023-08-21 20:43 UTC by AdamAdHocTeam

## Description of change

## How to test

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-0

## Checklists

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

2023-08-29 14:46 UTC, GarrettEHill approved these changes
The change looks good, My concern is this again is modifying approved FOIA-able records. I understand that current guidance states that our audit log is sufficient. But I still feel this is not good form to be modifying FOIA-able records.

2023-08-29 15:02 UTC, thewatermethod requested changes
Looks good! Can you also increment the LOCAL_STORAGE_CACHE_NUMBER to '0.3' in frontend/src/constants.js?

2023-08-30 14:30 UTC, AdamAdHocTeam commented
> LOCAL_STORAGE_CACHE_NUMBER

@thewatermethod the has been increased.

2023-08-30 14:30 UTC, thewatermethod approved these changes

2023-08-30 18:29 UTC, merged