[TTAHUB-2032] Add support type guidance to TR
HHS/Head-Start-TTADP pull request #1690
Opened 2023-08-24 19:14 UTC by AdamAdHocTeam

## Description of change

## How to test

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-0

## Checklists

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

2023-08-24 23:13 UTC, GarrettEHill approved these changes

2023-08-28 14:26 UTC, thewatermethod requested changes
Needs a small change, see comment

2023-08-30 16:38 UTC, AdamAdHocTeam commented on frontend/src/pages/SessionForm/pages/sessionSummary.js
> -          <Req />
@thewatermethod this should be fixed.

2023-08-30 17:49 UTC, thewatermethod approved these changes

2023-08-30 18:31 UTC, merged