[TTAHUB-2790] use closed_goal_merge_override feature flag to bypass filter
HHS/Head-Start-TTADP pull request #2080
Opened 2024-04-05 14:37 UTC by GarrettEHill

## Description of change
closed_goal_merge_override feature flag was not bypassing the filtering of goals to merge as it was intended

## How to test
with the feature flag on, closed and open matching curated goals can be merged. 

## Issue(s)

* [TTAHUB-2790](https://jira.acf.gov/browse/TTAHUB-2790)

## Checklists

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Before merge to main

- [ ] OHS demo complete
- [ ] Ready to create production PR

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

2024-04-05 15:02 UTC, thewatermethod commented
Looks to me like this change means that if the user who first looks at the recipient record has the feature flag, all subsequent users will see the groups as that user did (including closed curated goals, etc)

2024-04-05 22:43 UTC, GarrettEHill commented
> ~Looks to me like this change means that if the user who first looks at the recipient record has the feature flag, all subsequent users will see the groups as that user did (including closed curated goals, etc)~ nvm I misread what was happening here, sorry
> 
> There is code to do this already though, when the goal groups are created. It might be better to take a look at what the logic error is there.

It was working before, then some of the logic looks to have changed 2 months ago and now its not working. This make it work again.

2024-04-08 12:37 UTC, thewatermethod commented on src/services/goalSimilarityGroup.ts
> +  userHasFeatureFlag = false,
```suggestion
```

2024-04-08 12:38 UTC, thewatermethod commented on src/services/goalSimilarityGroup.ts
>      return true;
This entire filter should be removed, and replaced with

```js
goals: group.goals.map((goal) => goal.id)

2024-04-08 12:39 UTC, thewatermethod commented on src/services/goalSimilarityGroup.ts
> +    (gg: SimilarityGroup) => flattenSimilarityGroupGoals(gg, userHasFeatureFlag),
```suggestion
    (gg: SimilarityGroup) => flattenSimilarityGroupGoals(gg),
```

2024-04-08 12:40 UTC, thewatermethod commented
> It was working before, then some of the logic looks to have changed 2 months ago and now its not working. This make it work again.

@GarrettEHill 
The logic was not removed but moved. There is a column in the GoalSimilarityGroupGoals table (excluded if not admin.) Goals are flagged as excluded when they groups are created. The bug here is that the filter should have been removed from the GET service.

2024-04-09 01:49 UTC, thewatermethod requested changes
https://github.com/HHS/Head-Start-TTADP/pull/2086

2024-04-11 20:46 UTC, closed without merging