Init CD
HHS/Head-Start-TTADP pull request #46
Opened 2020-09-17 17:23 UTC by SarahJaine

**Description of change**
In short, this code adds an automated deployment pipeline.
- Add deploy job to circle ci config
- Call deploy job only on deployment branches (adhoc fork `main` for dev, HHS `main` for staging, HHS `prod` for prod)
- Change frontend `yarn build` command to change build output dir, tell `index.js` about this new dir location
- Add backend `yarn build` command to create compiled copy of BE files, changes `yarn start` to use new compiled index.js

**NOTE: Before this code is merged to the upstream HHS/Head-Start-TTADP repo, the HHS project circle ci env variables must be added for govcloud's deployer username/password and space name in order for the staging deploy to be successful.  The exact variable names should be:**
- CLOUDGOV_STAGING_USERNAME
- CLOUDGOV_STAGING_PASSWORD
- CLOUDGOV_STAGING_SPACE

**How to test**
Check out latest build for this branch on circle ci https://app.circleci.com/pipelines/github/adhocteam/Head-Start-TTADP/230/workflows/6b5cf689-4975-4e07-b9cf-054a9e4ff23b

**Issue(s)**
* Closes https://github.com/HHS/Head-Start-TTADP/issues/12

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [n/a] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [x] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

2020-09-17 17:29 UTC, SarahJaine commented on .circleci/config.yml
> +                - << pipeline.parameters.prod_git_branch >>
FWIW I'm not completely pleased with this filtering; it's not exactly skip/fail fast. This limits the deploy job to any branch named `main` or `production`.  In the deploy job, after assets are built and cf is installed, I then match for repo name.  This isn't really a security concern, as only our repo has access to dev deployment variables and only your repo has access to staging/prod vars.

2020-09-17 17:30 UTC, SarahJaine commented on README.md
> +The bulk of CI configurations can be found in this repo's [.circleci/config.yml](.circleci/config.yml) file.
I'll update this section to mention the security and accessibility reviews once those are in place on the CI pipeline.

2020-09-17 17:31 UTC, SarahJaine commented on README.md
> +Linting, unit tests and test coverage analysis are all run automatically on each push
I'll update this section to mention the security and accessibility reviews once those are in place on the CI pipeline.

2020-09-17 17:35 UTC, SarahJaine commented on .circleci/config.yml
> +        type: env_var_name
I tried echoing out a parameter that holds an env var, and circle ci still knows to redact it from the logs.

2020-09-18 15:00 UTC, rahearn requested changes
Awesome work. In addition to the change in routes, I'm wondering if the deploy step needs to set `NODE_ENV=production` for the two `yarn build` steps. Does build do things different for production vs development? And is that how it determines what to build?

2020-09-18 15:32 UTC, SarahJaine commented on .circleci/config.yml
> +            sudo dpkg -i cf-cli_amd64.deb
Thanks! I was interested to see your feedback on this line. I thought I might be missing something.

2020-09-18 15:35 UTC, SarahJaine commented on .circleci/config.yml
> +          command: cd frontend && yarn build
I could have _sworn_ I changed all these. I think this change got lost in a bad merge from upstream.  I'll fix.

2020-09-18 16:39 UTC, rahearn commented on README.md
> +| dev     | https://tta-smarthub.app.cloud.gov/ |
The route has to be globally unique, while app names are fine to be duplicated in different spaces.

I'm fine with your other method of setting a unique name and getting the route from that, but I'd like to get either that whole PR or just that change included in this PR or the deploy step will fail here.

2020-09-18 18:02 UTC, SarahJaine commented
> Awesome work. In addition to the change in routes, I'm wondering if the deploy step needs to set `NODE_ENV=production` for the two `yarn build` steps. Does build do things different for production vs development? And is that how it determines what to build?

Are you asking how/if I created an application build script specific to the deployed envs? For deployment, I'm using a few new commands (added this PR):
- for BE - `yarn build` uses babel to compile the files and puts them in a `build/server` dir. `yarn start` then runs that new compiled version of index.js to start the BE server.
- for FE - `yarn build` still  uses react-scripts like it does for local development, but those files are moved to a `build/server/client` dir.  I updated index.js so it can find those static files.

That setup is what's allowing me to not push (via .cfignore) our `src` dir (our normal non-compiled BE) and `frontend` dir (our normal non-compiled FE) onto the cf instance when it's deployed.

Does that help? Did I miss your question?

2020-09-18 18:13 UTC, SarahJaine commented on .circleci/config.yml
> +          command: cd frontend && yarn build
✅  Added in https://github.com/adhocteam/Head-Start-TTADP/pull/29

2020-09-18 18:14 UTC, SarahJaine commented on README.md
> +| dev     | https://tta-smarthub.app.cloud.gov/ |
Gotcha, moving this conversation to slack to figure out a merge strategy that doesn't make everyone crazy.

2020-09-18 18:20 UTC, rahearn commented
> * for BE - `yarn build` uses babel to compile the files

My comment is related to using something like `NODE_ENV=production yarn build` because sometimes (though it doesn't look like this project is currently set up that way) different babel plugins are configured for development vs production. Things like tree-shaking the front end in production, but not in development.

2020-09-18 18:26 UTC, rahearn commented on README.md
> +| dev     | https://tta-smarthub.app.cloud.gov/ |
Agreed here: https://gsa-tts.slack.com/archives/C017RJ4GEET/p1600453033043500?thread_ts=1600452758.040600&cid=C017RJ4GEET to make this change as part of another PR.

2020-09-18 18:36 UTC, SarahJaine commented
> > * for BE - `yarn build` uses babel to compile the files
> 
> My comment is related to using something like `NODE_ENV=production yarn build` because sometimes (though it doesn't look like this project is currently set up that way) different babel plugins are configured for development vs production. Things like tree-shaking the front end in production, but not in development.

We didn't add any configuration to the make the local/development and deployed/production builds of the babel plugins different.  To be honest, I haven't seen that before and didn't know it was a thing.  Do you want me to look into doing that as part of this PR?

2020-09-18 18:46 UTC, rahearn commented
> Do you want me to look into doing that as part of this PR?

nope, it might turn into a story in the future, but if the builds are the same for both environments right now we can leave it as be. Thanks

2020-09-18 18:48 UTC, rahearn commented
Definition of Done checklist:

- [x] The business and/or user value of a story has been met
- [x] CI pipeline green
- [x] Code is meaningfully tested
- [x] No linting errors or warnings
- [x] UI meets WCAG 2.1 - Levels A and AA
- [x] Code has deployed to a staging environment
- [x] [Architectural Decision Records](https://adr.github.io/) are written for major infrastructure decisions with [the Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md).
- [x] Boundary and Data Flow Diagrams are updated when a change invalidates the current version.
- [x] Public API methods are documented when added or changed.
- [x] OSCAL templates are completed when security controls are implemented or modified.

2020-09-18 18:59 UTC, rahearn approved these changes

2020-09-18 19:00 UTC, merged