Rename grantee to recipient
HHS/Head-Start-TTADP pull request #628
Opened 2021-11-17 20:29 UTC by jasalisbury

## Description of change

Update grantee to recipient on the frontend. Grantee TTA record page hasn't been released, so routes and variables can be changed without regard to compatibility between different versions of the FE and BE. Other places we aren't so lucky. A separate change which will take much longer will be coming down the pipe to address the grantee -> recipient change fully in the codebase, including updating routes/the database.

## How to test

View all pages and fill out reports. Make sure fields are labeled correctly and everything still works. Be sure to download a CSV and verify fields are not labeled with `grantee`. Values inside the form have not been updated nor has any data, both will be updated in a later PR.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-443

## Checklists

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

2021-11-22 17:14 UTC, AdamAdHocTeam approved these changes
Looks good. Just need to make sure the Recipient nav bar label matches the page header (as mentioned in meeting).

2021-11-22 17:19 UTC, jasalisbury commented
> We are calling them "non-recipients"? as in "recipient or non-recipient"?

Yeah I agree it seems a little strange. But yes I believe that is what was decided.

2021-11-22 17:20 UTC, thewatermethod approved these changes

2021-11-22 20:41 UTC, kryswisnaskas commented
Looks good. Everything works as advertised. 👍 

(waiting for Patrice's final word on the non-recipient)

2021-11-23 15:32 UTC, GarrettEHill approved these changes

2021-12-01 22:29 UTC, GarrettEHill approved these changes

2021-12-02 16:08 UTC, kryswisnaskas requested changes
The wording looks good! 👍

2021-12-02 16:13 UTC, kryswisnaskas approved these changes

2021-12-14 15:44 UTC, thewatermethod commented on frontend/src/pages/ApprovedActivityReport/index.js
> +        let recipientType = data.activityRecipients[0].grantId ? 'Recipient' : 'Non-recipient';
poking around the backend changes, noticed this

2021-12-16 21:41 UTC, merged