CI: Add Dynamic Security Scan (#44)
HHS/Head-Start-TTADP pull request #94
Opened 2020-10-15 15:07 UTC by SarahJaine

**Description of change**
Adds owasp zap for dynamic security scan to the CI pipeline.  Adds ADR to propose eslint, yarn audit, and owasp zap as tools.

**How to test**
See passing CI in CircleCI https://app.circleci.com/pipelines/github/adhocteam/Head-Start-TTADP?branch=sj-ci-owasp
For an example of OWASP failure triggering pipeline failure see https://app.circleci.com/pipelines/github/adhocteam/Head-Start-TTADP/331/workflows/dfc090ee-541c-4893-8b00-50d9b7df01d6/jobs/1105

**Issue(s)**
* closes https://github.com/HHS/Head-Start-TTADP/issues/11

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [n/a] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [x] Documentation updated - _Added ADR and line in README to point to ADR_
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

2020-10-15 16:09 UTC, rahearn requested changes
Great job on getting the server setup and scanning in CI. One thing I noticed though, is that the app while running in the dynamic_security_scan step is returning a 500 error so it's not scanning a good page. I pulled this error from the server logs that I think should help fix it:

`Error: secret option required for sessions`

`process.env.SESSION_SECRET` likely needs to be set. It can be set in the docker-compose-test.yml file though, since it's not a real secret in this environment.

The only other change I'd like is to re-number the ADR.

2020-10-15 16:09 UTC, rahearn commented on docs/adr/0008-security-scans.md
> +# 8. Security Scans
Please renumber (and rename the file) to be ADR 9. 8 is duplicated now.

2020-10-15 21:38 UTC, SarahJaine commented
> Great job on getting the server setup and scanning in CI. One thing I noticed though, is that the app while running in the dynamic_security_scan step is returning a 500 error so it's not scanning a good page. I pulled this error from the server logs that I think should help fix it:
> 
> `Error: secret option required for sessions`
> 
> `process.env.SESSION_SECRET` likely needs to be set. It can be set in the docker-compose-test.yml file though, since it's not a real secret in this environment.
> 
> The only other change I'd like is to re-number the ADR.

Yep, that fixed it! Changes proposed in new Ad Hoc PR https://github.com/adhocteam/Head-Start-TTADP/pull/46

2020-10-19 13:27 UTC, rahearn approved these changes

2020-10-19 13:27 UTC, merged